### PR TITLE
Some outdated, request takeover.

### PR DESCRIPTION
**Pull request by RSKYS**
PHAZOR audio backend audio/tauonmb requires libopenmpt which is available at https://github.com/RSKYS/SBo-pre/releases

image 
image

Also I'd like to takeover packages I mentioned because I check them at every new release of tauon;
If it's not possible, please don't close this pull; tell me what to edit and I'll modify patch.
Regards, ~red

### CODE REVIEW

**Comment by Ponce** [comment]
Hi Pouria, I'll try to clarify a few things:
- this repository contains SlackBuilds for Slackware current soon-to-become Slackware 15.0: this Slackware version already contains python3 so it doesn't need to be added to the REQUIRES variable of the *.info files;
- you cannot takeover the packages you sent the pull request for because the maintainer is another person: you have to ask permission to the maintainer and he has to agree;
- you cannot compile stuff while running the doinst.sh file: the phazor library must be compiled in the SlackBuild and the resulting library packaged with the rest of the files, we don't want untracked files in the system.
- send one commit for every SlackBuild interested (also in the same pull request), not one global commit for many different SlackBuilds.
If I notice other things I'll add them below!

**Comment by RSKYS** [comment]
As result I can only modify my existing packages
Also I'm kinda new to takeover thing, how to prove if I ever takeover? I better notify them I guess

For that my work will get hard, I'm not sure slack support that but what you're asking me is create PHAZOR SlackBuild depended on libopenmpt which is not sane because it's exclusive to tauon
I'll try to see I can bind it to install or not..

When will Slackware 15.0 release? Is it surprise? :)

**Comment by Ponce** [comment]
> As result I can only modify my existing packages

yes.

> Also I'm kinda new to takeover thing, how to prove if I ever takeover? I better notify them I guess

you should get in touch with them by mail asking for permission: wait at least two weeks for a reply.

> For that my work will get hard, I'm not sure slack support that but what you're asking me is create PHAZOR SlackBuild depended on libopenmpt which is not sane because it's exclusive to tauon (It's tauon part inside it, tbh nothing seperatable)
> I'll try to see I can bind it to package or not..

you can do a separate SlackBuild and introduce it as a dependency or you can build it in the same tauon.SlackBuild, whatever you feel more comfortable with.

> When will Slackware 15.0 release? Is it surprise? :)

yes, it has always been like that, there's no fixed Slackware release date: the official mantra is "it's ready when it's ready".

**Comment by RSKYS** [comment]
Fine.. I'll ask them and wait for 2 weeks and if I don't get result, I'll let you know.
I'm on current almost for a year; Wish there were faster way cause not having submission is just pain and I'd even like to submit through GitHub directly..
But my hard guess is Slack birthday or something.
I'm closing this, thx.

**Pull request closed without merging**
