### PR TITLE
offlineimap python2 fix

### PR DESCRIPTION
**Pull request by ardrabczyk**
- **network/offlineimap: Install with python2**
- **python/python2-six: Added (Python 2 and 3 compatibility utilities)**
- **network/offlineimap: Add python2-six dependency**

### CODE REVIEW

**Comment by ardrabczyk** [comment]
@Ponce will you solve the conflict or should I restore offlineimap myself? Or maybe you don't want to merge this PR?

**Comment by Ponce** [comment]
> @Ponce will you solve the conflict or should I restore offlineimap myself? Or maybe you don't want to merge this PR?

I added python2-six and reinstated offlineimap: as offlineimap is dead an offlineimap3 is maintained I would have preferred to have an offlineimap3 script.
Also, like @willysr said, the maintainer abandoned the script so it will be most probably removed not so far in time...
Enjoy it while it last! ;-)

**Comment by ardrabczyk** [comment]
But why should it be removed? Here https://lists.slackbuilds.org/pipermail/slackbuilds-users/2024-July/029557.html it says that the policy is to keep packages that have been abandoned by upstream as long as they build and work.

**Comment by Ponce** [comment]
yes that says that it should not be necessarily removed if it's not maintained anymore **upstream**.
it should be definitely removed if it's not maintained anymore **on SBo** (or we will be forced to maintain it us admins!): feel free to step in as a maintainer if you wish to keep it on SBo.

**Pull request closed without merging**
