### PR TITLE
Updated to build with qt5 and python3.

### PR DESCRIPTION
**Pull request by newHeiko**
Hi Matteo,

I hope this kind of PR addresses all your issues. It also now merges into the pre-existing FreeCAD-branch instead of master.

I'm closing the other FreeCAD PR in favor of this one.

File contents is the same.

Enjoy Christmas,
Heiko

### CODE REVIEW

**Comment by lockywolf** [comment]
Sorry, I am confused a bit.
This is not in the main tree yet, right?

**Comment by newHeiko** [comment]
> Sorry, I am confused a bit.
> This is not in the main tree yet, right?

Right. I still have a few things to fix, in particular getting all the dependencies working with python3.

We'll see when I get to it...

Sorry for the delay,
Heiko

**Comment by lockywolf** [comment]
Can I help with this slackbuild somehow? Which deps need to be made compatible with python3?

**Comment by newHeiko** [comment]
That would be great. Pivy is the one missing, and then I'll need to check if FreeCAD still builds with the new Pivy.

Cheers,
Heiko

**Comment by Ponce** [comment]
this has been closed by mistake when the FreeCAD branch has been deleted...

**Pull request closed without merging**
