### PR TITLE
Free cad

### PR DESCRIPTION
**Pull request by newHeiko**
...and here comes FreeCAD.

I certainly hope they'll release 0.19 soon so all this backporting to fix build failures has an end. Also, they fixed a lot of boost and qt deprecation warnings, but that would mean touching almost every file...

Cheers,
Heiko

### CODE REVIEW

**Comment by Ponce** [comment]
@newHeiko : sorry, I have difficulties understanding what happens :D
can you send me just one patch for graphics/FreeCAD that applies on top of what we have on SBo?

https://slackbuilds.org/repository/14.2/graphics/FreeCAD/

via mail is fine too!

**Comment by newHeiko** [comment]
Same here - it's about a 900-line-patch over SBo...

If you want, I can also rebase this on SBo-git/FreeCAD, which already includes two of those changes.

Cheers,
Heiko

**Comment by Ponce** [comment]
sorry @newHeiko , I'll paste here a question that was in the LQ topic and that maybe you missed:
"but, what I had asked myself too when I had a look, do some of the python FreeCAD dependencies can still use python-2.x while others use python-3.x?"

**Comment by newHeiko** [comment]
Closing this in favor of #94 - this merges into master, #94 into FreeCAD. Apart from that, they are the same.

Merry Christmas,
Heiko

**Pull request closed without merging**
