### PR TITLE
audio/quodlibet: Patch for Python 3.12 compatibility.

### PR DESCRIPTION
**Pull request by nick8325**

### CODE REVIEW

**Comment by nick8325** [comment]
Oh, it looks like the pull request has gone weird since it includes the "20241124.1 global branch merge" commit, want me to rebase on 20241130.1?

**Comment by Ponce** [comment]
> Oh, it looks like the pull request has gone weird since it includes the "20241124.1 global branch merge" commit, want me to rebase on 20241130.1?

there's no problem, I'll just take the commit.

what puzzles me is that on my installation quodlibet builds fine against python-3.12.x with no need of any patches: do you still want me to push this?

**Comment by nick8325** [comment]
Without the patch it builds but fails at runtime with some kind of module import error - at least on my machine. Are you also able to run it without the patch?

**Comment by Ponce** [comment]
> Without the patch it builds but fails at runtime with some kind of module import error - at least on my machine. Are you also able to run it without the patch?

actually no: sorry I didn't try it before...
thanks for the patch: I pushed it in a dedicated branch!

**Pull request closed without merging**
