### PR TITLE
libraries/uriparser: Fixed REQUIRES.

### PR DESCRIPTION
**Pull request by idlemoor**
Signed-off-by: David Spencer <baildon.research@googlemail.com>

### CODE REVIEW

**Comment by idlemoor** [comment]
Good Morning Matteo :-)
As far as I can tell graphviz is a hard dependency... sorry if I'm wrong?

**Comment by Ponce** [comment]
I don't know how I close this :-(
yes, you're right! as I have done my usual rebasing dance I'll add the commit to the branch manually.
thanks as usual!

**Comment by idlemoor** [comment]
Hey Thanks Matteo,
I had fifty more (!) to send to you this afternoon but I want to retest
them with the new -current, so you can have a quiet evening :D

Thanks again
-D.

**Comment by Ponce** [comment]
fifty :o many thanks in advance David! :D

**Pull request closed without merging**
