### PR TITLE
network/aria2: Updated for version 1.28.0

### PR DESCRIPTION
**Pull request by jak3**
No major changes.

### CODE REVIEW

**Comment by Ponce** [comment]
hi Giacomo,

you should propose version bumps of the various SlackBuilds each one to their own maintainer, in this case @willysr : if they are ok for them I have no problem merging them in my personal branch so that they will go on SBo at the next update.

**Comment by willysr** [comment]
Thanks @jak3. I will update to 1.29.0 soon on my branch

**Comment by jak3** [comment]
@Ponce OK, thanks. Sorry for the drawback, it is my first "contribution". 
@willysr Your welcome.

**Comment by Ponce** [comment]
@jak3 np, any contribution is welcomed :)

**Pull request closed without merging**
