### PR TITLE
Pyside2

### PR DESCRIPTION
**Pull request by newHeiko**
Somehow I managed to make a mess of my commit history again... gotta learn git, sorry for that.

But anyway, here's pyside2, replacing pyside, pyside-tools and shiboken, which don't work with qt5 any more.

Required for FreeCAD, which will be the next PR.

Cheers,
Heiko

### CODE REVIEW

**Comment by Ponce** [comment]
@newHeiko : sorry, I have difficulties understanding what happens :D
can you send me just one tarball with the pyside2 SlackBuild, like at submission time on SBo?
via mail is fine too!

**Comment by newHeiko** [comment]
I'm experimenting with git - does this help?

Otherwise I'll send you a tar.gz-archive of the new package via eMail.

Cheers,
Heiko

**Comment by Ponce** [comment]
the stuff in the commit is pretty much ok, it's the commit message that , to follow SBo standards, should be an one-liner, something like:
"python/pyside2: Added (LGPL python bindings for Qt5)."

also the branch for which you are doing the pull request, newHeiko:pyside2, should be merged not on master but on a dedicated pyside2 branch in this repository.

**Comment by newHeiko** [comment]
I can't create a new branch for pyside2 in your repo, since I don't have those rights.

So I'll send you the tar.gz via eMail, closing this.

Merry Christmas,
Heiko

**Pull request closed without merging**
